### ISSUE TITLE
Port over grok patterns from ES

### ISSUE THREAD

**Issue by ycombinator** [elastic/go-grok#9]
Port over grok patterns, e.g. https://github.com/elastic/elasticsearch/blob/main/libs/grok/src/main/resources/patterns/ecs-v1/junos to this repository.

**Comment by michalpristas** [comment]
closing, 
nagios and zeek moved to separate issues:
https://github.com/elastic/go-grok/issues/16
https://github.com/elastic/go-grok/issues/17
